# Generated by Django 5.0.4 on 2024-05-07 21:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(blank=True, default=None, related_name='group_membership', to=settings.AUTH_USER_MODEL),
        ),
    ]
