# Generated by Django 5.0.4 on 2024-05-25 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_rename_children_child'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('audio_id', models.IntegerField(null=True, unique=True)),
                ('audio', models.FileField(upload_to='audio/')),
                ('score', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_id', models.IntegerField(null=True, unique=True)),
                ('word', models.CharField(max_length=20, null=True)),
                ('audio', models.FileField(upload_to='audio/')),
            ],
        ),
    ]
