# Generated by Django 5.0.4 on 2024-05-25 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_audiofile_word'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='level',
            field=models.IntegerField(null=True),
        ),
    ]
