# Generated by Django 5.0.4 on 2024-05-25 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_word_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='audio',
        ),
        migrations.RemoveField(
            model_name='word',
            name='word_id',
        ),
    ]
