# Generated by Django 5.0.4 on 2024-05-24 17:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("record", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Word",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("word_id", models.IntegerField(null=True, unique=True)),
                ("word", models.CharField(max_length=20, null=True)),
                ("audio", models.FileField(upload_to="audio/")),
            ],
        ),
        migrations.AddField(
            model_name="audiofile",
            name="audio_id",
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
