# Generated by Django 5.0.4 on 2024-05-24 21:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("record", "0002_word_audiofile_audio_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="audiofile",
            name="transcription",
        ),
    ]
