# Generated by Django 5.0.4 on 2024-05-24 22:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("record", "0003_remove_audiofile_transcription"),
    ]

    operations = [
        migrations.AddField(
            model_name="audiofile",
            name="score",
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
