# Generated by Django 5.0.4 on 2024-05-24 23:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("record", "0004_audiofile_score"),
    ]

    operations = [
        migrations.AlterField(
            model_name="audiofile",
            name="score",
            field=models.IntegerField(null=True),
        ),
    ]
