# Generated by Django 5.0.4 on 2024-06-01 10:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("record", "0006_remove_word_audio_remove_word_word_id_word_level_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="word",
            name="word_vocal",
            field=models.FileField(null=True, upload_to="recordings/"),
        ),
    ]
